/**
 * Generates ../generated/types.ts from ../schemas. Run with `npm run codegen`.
 * Every schema gets a title derived from its path unless it declares one:
 *   signaling/PAIR_REQUEST.json -> PairRequestPayload
 *   datachannel/mouse_move.json -> MouseMoveMessage
 *   server/auth_ok.json         -> AuthOkFrame
 */
import { compile } from 'json-schema-to-typescript';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const SCHEMA_DIR = join(ROOT, 'schemas');
const BASE = 'https://prc.local/schemas/';

function pascal(s: string): string {
  return s
    .split(/[_-]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
    .join('');
}

function titleFor(rel: string): string {
  const parts = rel.split('/');
  const file = parts[parts.length - 1]!.replace(/\.json$/, '');
  const dir = parts.length > 1 ? parts[0] : '';
  if (dir === 'signaling') return `${pascal(file)}Payload`;
  if (dir === 'datachannel') return `${pascal(file)}Message`;
  if (dir === 'server') return `${pascal(file)}Frame`;
  return pascal(file);
}

function readSchema(rel: string): Record<string, unknown> {
  const schema = JSON.parse(readFileSync(join(SCHEMA_DIR, rel), 'utf8')) as Record<string, unknown>;
  if (typeof schema.title !== 'string') schema.title = titleFor(rel);
  return schema;
}

const prcResolver = {
  order: 1,
  canRead: /^https:\/\/prc\.local\/schemas\//,
  read(file: { url: string }): string {
    const rel = file.url.slice(BASE.length).replace(/#.*$/, '');
    return JSON.stringify(readSchema(rel));
  },
};

const properties: Record<string, { $ref: string }> = {
  envelope: { $ref: `${BASE}envelope.json` },
  qr_payload: { $ref: `${BASE}qr-payload.json` },
};
for (const dir of ['signaling', 'datachannel', 'server']) {
  for (const f of readdirSync(join(SCHEMA_DIR, dir)).sort()) {
    properties[`${dir}_${f.replace(/\.json$/, '')}`] = { $ref: `${BASE}${dir}/${f}` };
  }
}

const catalog = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: `${BASE}catalog.json`,
  title: 'ProtocolCatalog',
  description: 'Index of every wire message type. Exists only so codegen emits all types from one root.',
  type: 'object',
  properties,
  additionalProperties: false,
};

const ts = await compile(catalog as never, 'ProtocolCatalog', {
  cwd: SCHEMA_DIR,
  bannerComment: '/* Generated by scripts/codegen.ts from schemas/. Do not edit by hand. Run `npm run codegen`. */',
  additionalProperties: false,
  strictIndexSignatures: true,
  maxItems: -1,
  $refOptions: { resolve: { prc: prcResolver } },
});

mkdirSync(join(ROOT, 'generated'), { recursive: true });
writeFileSync(join(ROOT, 'generated', 'types.ts'), ts);
console.log(`wrote generated/types.ts (${ts.length} bytes, ${Object.keys(properties).length} message types)`);
